[package]
name = "frostx"
version = "0.1.0"
edition = "2021"
description = "Project lifecycle manager - archives and cleans inactive project folders"
license = "MIT"

[[bin]]
name = "frostx"
path = "src/main.rs"

[[bin]]
name = "gen_man"
path = "src/bin/gen_man.rs"

[[bin]]
name = "gen_completions"
path = "src/bin/gen_completions.rs"

[dependencies]
anyhow       = "1"
chrono       = { version = "0.4", features = ["serde"] }
clap         = { version = "4", features = ["derive"] }
clap_complete= "4"
clap_mangen  = "0.3"
dialoguer    = "0.12"
directories  = "6"
flate2       = "1"
#indicatif   = "0.18"
owo-colors   = { version = "4", features = ["supports-colors"] }
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
tar          = "0.4"
thiserror    = "2"
toml         = "1"
uuid         = { version = "1", features = ["v4", "serde"] }
walkdir      = "2"
xz2          = "0.1"
zstd         = "0.13"

[[test]]
name = "integration"
path = "tests/integration/main.rs"

[dev-dependencies]
tempfile    = "3"

[profile.release]
strip = true
lto   = true
